### ISSUE TITLE
str2str conversion problem with Neo-M8T

### ISSUE THREAD

**Issue by bench2014** [tomojitakasu/RTKLIB#115]
Hi,
I am using the Neo-M8T and have some strange problems..
Linux, Debian 8.1, 3.16.0-amd64
By converting from UBX--> RTCM3, nothing happens after entering the command in the terminal. Like I would press enter and a new command line appears...
sudo ./str2str -in serial://ttyACM0#ubx -out tcpsvr://:9000#rtcm3

When I remove ...#rtcm3, so only: 
sudo ./str2str -in serial://ttyACM0#ubx -out tcpsvr://:9000
I get the following result:
stream server start
2015/10/30 07:40:43 [CW---]          0 B       0 bps 
2015/10/30 07:40:48 [CW---]     132656 B  210827 bps (1) waiting... 
2015/10/30 07:40:53 [CW---]     264964 B  211161 bps (1) waiting... 
...

It also seems, that strsvr(ubx->rtcm3) within windows works also.
Any Idea?

Thanks in advance!
Greetings from Austria
Benjamin

**Comment by tomojitakasu** [comment]
Use the option -msg to specify the output RTCM messages.

**Comment by ivanskj** [comment]
Same problem here, i reverted to 2.4.2 p11. Was a problem with the #format in str2str. Works with 2.4.2p11

**Comment by gsfjim** [comment]
Also having rtcm3 conversion problem with skytraq (NS-Raw). Seems to segfault whenever rtcm3 is specified as output. In my case I am sending output to an ntrip caster, but the segfault occurs even if just outputting to file.

./str2str -in serial://ttyUSB0:38400:8:n:1:off#stq -out ntrips://:password@ntrip.mydomain.net:2101/MTPT01#rtcm3 -msg 1002,1006,1019 -p 48.34826918 292.0471986 108.7775614 
works in str2str from rtklib 2.4.2 (but with known bug in 2.4.2 relating to position sent being wrong) but results in segfault with str2str in 2.4.3b5.  Stripping the -msg and -p arguments makes no difference, but removing the #rtcm3 allows it to run without segfaulting but of course no conversion.

gdb debugging results in:
jim@jim:~/Downloads/RTKLIB-rtklib_2.4.3/app/str2str/gcc$ gdb -args ./str2str -in serial://ttyUSB0:38400:8:n:1:off#stq -out ntrips://:password@ntrip.mydomain.net:2101/MTPT01#rtcm3 -msg 1002,1006,1019 -p 48.34826918 292.0471986 108.7775614 
GNU gdb (Ubuntu 7.10-1ubuntu2) 7.10
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
....
Reading symbols from ./str2str...done.
(gdb) run
Starting program: /home/jim/Downloads/RTKLIB-rtklib_2.4.3/app/str2str/gcc/str2str -in serial://ttyUSB0:38400:8:n:1:off\#stq -out ntrips://:password@ntrip.mydomain.net:2101/MTPT01\#rtcm3 -msg 1002,1006,1019 -p 48.34826918 292.0471986 108.7775614 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
__strcpy_chk () at ../sysdeps/x86_64/strcpy_chk.S:68
68      ../sysdeps/x86_64/strcpy_chk.S: No such file or directory.
(gdb) backtrace
#0  __strcpy_chk () at ../sysdeps/x86_64/strcpy_chk.S:68
#1  0x0000000000403b2e in strcpy (__src=<optimized out>, __dest=0x7ffff7fa1c50 "") at /usr/include/x86_64-linux-gnu/bits/string3.h:110
#2  main (argc=<optimized out>, argv=<optimized out>) at ../str2str.c:250
(gdb) frame 0
#0  __strcpy_chk () at ../sysdeps/x86_64/strcpy_chk.S:68
68      in ../sysdeps/x86_64/strcpy_chk.S
(gdb) frame 1
#1  0x0000000000403b2e in strcpy (__src=<optimized out>, __dest=0x7ffff7fa1c50 "") at /usr/include/x86_64-linux-gnu/bits/string3.h:110
110       return __builtin___strcpy_chk (__dest, __src, __bos (__dest));
(gdb) frame 2
#2  main (argc=<optimized out>, argv=<optimized out>) at ../str2str.c:250
250             strcpy(conv[i]->out.sta.antdes,ant[0]);
(gdb) 

I am "out of my depth" at this point but happy to try any suggestions and report back

**Comment by bench2014** [comment]
Solved by using the actual str2str from the master branch and not the str2str of the 2.4.3 dev. branch.
Greetings
Benjamin

**Comment by gsfjim** [comment]
Yes, thank you. The comment was just to add detail and narrow the issue in your original report which was in reference to 2.4.3, not 2.4.2(master branch). As stated rtcm3 conversion works with 2.4.2p11 (master branch), although with known position (-p switch) bug but crashes with 2.4.3b5 (development branch) when converting to RTCM3
