### ISSUE TITLE
android app crashes when stopping service

### ISSUE THREAD

**Issue by Chaos99** [tomojitakasu/RTKLIB#171]
Both when using the ''options' soft button as well as the menu, stopping the service causes the app to crash.

Package version: 23
Package version name: 1.0 alpha 23

java.lang.NullPointerException

Source file: RtkNaviService.java
Source class: gpsplus.rtkgps.RtkNaviService
Line number: 295

Stack trace (abbriviated):
java.lang.Runtime Exception: Unable to start service
gpsplus.rtkgps.RtkNaviService@2e747f11 with Intent
  { act=gpsplus.rtkgps.RtkNaviService.STOP cmp=gpsplus.rtkgps/.RtkNaviService }:
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean gpsplus.rtkgps.DemoModeLocation.isInDemoMode()' on a null object reference 
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3320)
at android.app.ActivityThread.access$2200(ActivityThread.java:177)
at android.app.ActivityThread.$H.handleMessage(ActivityThread.java:1549)
at android.os.Handler.dispatchMessage(Handler.java:102)
at [...]
Caused by:
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean gpsplus.rtkgps.DemoModeLocation.isInDemoMode()' on a null object reference 
at gpsplus.rtkgps.RtkNaviService.processStop(RtkNaviService.java:295)
at gpsplus.rtkgps.RtkNaviService.onStartCommand(RtkNaviService.java:153)
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3303)
[...]

**Comment by tomojitakasu** [comment]
The problem might be due to RTKGPS+, which is an RTKLIB front-end on Android. Please contact the author of RTKGPS+.

https://github.com/eltorio/RtkGps

**Comment by Chaos99** [comment]
Sorry for the confusion. I'll move the ticket there.
